baseurl = "http://pliutau.com/"
languageCode = "en-us"
title = "Aliaksandr Pliutau"
comments = true

[params]
  disqus = "pliutau"
  ga = "UA-72731922-1"
  subscribe_rss = "/index.xml"
  subscribe_email = "a.pliutau@gmail.com"
