title = "Alex Pliutau"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Alex Pliutau"
disqusShortname = "pliutau"
paginate= 50

[Author]
    name = "Alex Pliutau"
    profile = "https://pliutau.com"

[Params]
    intro = false
    github = "https://github.com/plutov"
    linkedin = "https://linkedin.com/in/pltvs/"
    twitter = "https://twitter.com/pliutau"
    youtube = "https://www.youtube.com/packagemain"
    stackoverflow = "https://stackoverflow.com/users/350294/pltvs"
    email = "a.pliutau@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    description = "Alex Pliutau's blog. My thoughts about golang, programming, backend, devops, docker, etc."

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2

[[menu.main]]
    name = "Subscribe"
    url = "https://eepurl.com/cDoD09"
    weight = 3

[[menu.main]]
    name = "Buy me a coffee"
    url = "https://www.buymeacoffee.com/packagemain"
    weight = 4
